use bevy::prelude::*;
use bevy_asset_loader::asset_collection::AssetCollection;

#[derive(AssetCollection, Resource)]
pub struct Atlas {
    #[asset(texture_atlas_layout(
        tile_size_x = 32,
        tile_size_y = 32,
        columns = 4,
        rows = 4,
        padding_x = 1,
        padding_y = 1,
    ))]
    pub layout: Handle<TextureAtlasLayout>,
    #[asset(path = "tilemap.png")]
    pub texture: Handle<Image>,
}

#[derive(Clone, PartialEq)]
pub enum Texture {
    LeftTopCorner = 0,
    RightTopCorner = 1,
    LeftBottomCorner = 2,
    RightBottomCorner = 3,
    TopEdge = 4,
    BottomEdge = 5,
    LeftEdge = 6,
    RightEdge = 7,
    Center = 8,
    Coin = 9,
    Snake = 10,
    Cat = 11,
    Column = 12,
    Heart = 13,
    Sword = 14,
    Shield = 15,
}

#[derive(Resource)]
pub struct GameBoardLayers {
    pub base_layer: Vec<Vec<Texture>>,
    pub object_layer: Vec<Vec<Option<Texture>>>,
}

impl FromWorld for GameBoardLayers {
    fn from_world(_world: &mut World) -> Self {
        Self {
            base_layer: vec![
                vec![
                    Texture::LeftTopCorner,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::TopEdge,
                    Texture::RightTopCorner,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftEdge,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::Center,
                    Texture::RightEdge,
                ],
                vec![
                    Texture::LeftBottomCorner,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::BottomEdge,
                    Texture::RightBottomCorner,
                ],
            ],
            object_layer: vec![
                vec![None, None, None, None, None, None, None, None, None, None],
                vec![None, None, None, None, None, None, None, None, None, None],
                vec![
                    None,
                    None,
                    Some(Texture::Column),
                    Some(Texture::Column),
                    Some(Texture::Column),
                    None,
                    None,
                    None,
                    None,
                    None,
                ],
                vec![None, None, None, None, None, None, None, None, None, None],
                vec![None, None, None, None, None, None, None, None, None, None],
                vec![
                    None,
                    None,
                    None,
                    None,
                    None,
                    Some(Texture::Cat),
                    None,
                    None,
                    None,
                    None,
                ],
                vec![
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    Some(Texture::Snake),
                    None,
                    None,
                ],
                vec![
                    None,
                    None,
                    Some(Texture::Coin),
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                ],
                vec![None, None, None, None, None, None, None, None, None, None],
                vec![None, None, None, None, None, None, None, None, None, None],
            ],
        }
    }
}
